stages:
  - test
  - build
  - tag

.python:
  image: python:3.7
  stage: test
  cache:
    key: pip-cache
    paths:
      - .cache/pip
      - .pytest_cache
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install poetry
    - poetry debug:info
    - poetry config settings.virtualenvs.create false
    - poetry --no-interaction install

pytest:
  extends: .python
  script:
    - pytest --junitxml=pytest.xml
    - coveralls
  artifacts:
    reports:
      junit: pytest.xml
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

flake8:
  extends: .python
  script:
    - flake8 --format=junit-xml --output-file flake8.xml
  artifacts:
    reports:
      junit: flake8.xml

black:
  extends: .python
  cache:
    key: black-cache
    paths:
    - .cache/pip
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install -U black
  script:
    - black --check --verbose .
  artifacts: {}

.docker:
  image: docker:stable
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  extends: .docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

tag latest:
  extends: .docker
  stage: tag
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
