language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install --dev --system

script:
  - python manage.py migrate
  - coverage run --source='.' manage.py test podcasts.tests

sudo: false

after_success:
    coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5ad277b8006a8c307f3
    on_success: change
    on_failure: always
    on_start: never
