language: python
python:
  - '3.6'
sudo: required
env:
  global:
  - DATABASE_URL="sqlite:////tmp.db"
  - ENVIRONMENT=Production

install:
  - pip install poetry coveralls
  - poetry config settings.virtualenvs.create false
  - poetry --no-interaction install
  - npm install
  - chmod +x prepare.sh
  - ./prepare.sh

script:
  - coverage run --source='.' manage.py test podcasts.tests

after_success:
  - coveralls --data_file=.coverage --config_file=.coveragerc
