version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: tapedrive
      POSTGRES_USER: tapedrive
      POSTGRES_PASSWORD: t4pedr1ve
  web:
    build: .
    image: registry.gitlab.com/janw/tapedrive
    restart: always
    volumes:
      - ./media:/data
    ports:
      - "8273:8273"
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "postgres://tapedrive:t4pedr1ve@db/tapedrive"
