
POETRY=poetry
REQUIREMENTS_FILE=$(CURDIR)/requirements.txt

requirements:
	@echo "# AUTO-GENERATED BY POETRY EXPORT; DO NOT MODIFY MANUALLY" \
		> "$(REQUIREMENTS_FILE)"
	@$(POETRY) export -f requirements.txt >> "$(REQUIREMENTS_FILE)"


CURRENT_REQS = $(shell $(POETRY) export -f requirements.txt)
FILE_REQS = $(shell tail -n +2 $(REQUIREMENTS_FILE))

check_requirements:
ifneq "$(CURRENT_REQS)" "$(FILE_REQS)"
	@echo "requirements.txt not up to date"
	@exit 1
endif
	@exit 0
