# Generated by Django 2.0.5 on 2018-05-25 19:14

from django.db import migrations
from django.contrib.auth import get_user_model

import os
import random
import string


DUMMY_EMAIL = 'noreply@tapedrive.example'


def create_superuser(apps, schema_editor):
    User = get_user_model()
    username = os.getenv('TAPEDRIVE_ADMIN_USER', 'admin')
    random_password = ''.join([random.SystemRandom().choice(
        string.ascii_uppercase + string.ascii_lowercase + string.digits)
        for i in range(10)])
    print('Creating initial user:', username, '// pass:', random_password)
    User.objects.create_superuser(username, DUMMY_EMAIL, random_password)


def delete_superuser(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.get(email=DUMMY_EMAIL).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180502_1736'),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
