# Generated by Django 2.0.13 on 2019-08-18 09:15

from django.db import migrations, models
import podcasts.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '__first__'),
        ('users', '0003_create_initial_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Reduce eye strain at night, increase awesomeness by day.', verbose_name='Dark Mode'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_security_policy',
            field=models.CharField(choices=[('a', 'Allow All'), ('f', 'Allow First-Party'), ('n', 'Allow None')], default='f', help_text='How to load external images in show notes, etc.', max_length=1, verbose_name='Image Security Policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_podcasts',
            field=models.ManyToManyField(related_name='followers', to='podcasts.Podcast', verbose_name='Added Podcasts'),
        ),
        migrations.AddField(
            model_name='user',
            name='playback_seek_backward_by',
            field=podcasts.models.IntegerRangeField(blank=True, default=30, null=True, verbose_name='Seek Duration Backward'),
        ),
        migrations.AddField(
            model_name='user',
            name='playback_seek_forward_by',
            field=podcasts.models.IntegerRangeField(blank=True, default=45, null=True, verbose_name='Seek Duration Forward'),
        ),
        migrations.AddField(
            model_name='user',
            name='sort_order_episodes',
            field=models.CharField(choices=[('Content', (('title', 'Title'),)), ('Metadata', (('downloaded', 'Download Date (Earliest First)'), ('-downloaded', 'Download Date (Latest First)'), ('published', 'Publishing Date (Earliest First)'), ('-published', 'Publishing Date (Latest First)'), ('itunes_duration', 'Duration (Shortest First)'), ('-itunes_duration', 'Duration (Longest First)')))], default='-published', help_text='Determines the sorting of episodes on podcast detail pages', max_length=16, verbose_name='Sort Episodes By'),
        ),
        migrations.AddField(
            model_name='user',
            name='sort_order_podcasts',
            field=models.CharField(choices=[('Content', (('title', 'Title'),)), ('Metadata', (('last_episode_date', 'Last Published Episode'), ('num_episodes', 'Number of Episodes')))], default='title', help_text='Determines the sorting of podcasts in the podcasts list', max_length=16, verbose_name='Sort Podcasts By'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_podcasts',
            field=models.ManyToManyField(related_name='subscribers', to='podcasts.Podcast', verbose_name='Subscribed Podcasts'),
        ),
    ]
