# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv coveralls
            pipenv install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile" }}

      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py migrate
            coverage run --source='.' manage.py test podcasts.tests
          environment:
            DATABASE_URL: mysql://root@127.0.0.1:3306/circleci
            ENVIRONMENT: Production

      - store_artifacts:
          path: test-reports
          destination: test-reports

