# Generated by Django 2.0 on 2018-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcast_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='interested_podcasts',
            field=models.ManyToManyField(related_name='followers', to='podcasts.Podcast', verbose_name='Added Podcasts'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='subscribed_podcasts',
            field=models.ManyToManyField(related_name='subscribers', to='podcasts.Podcast', verbose_name='Subscribed Podcasts'),
        ),
    ]
