# Generated by Django 2.0.5 on 2018-05-26 19:27

from django.db import migrations, models
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_switch_to_utf8mb4_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='/data', recursive=True, verbose_name='File Location'),
        ),
        migrations.AlterField(
            model_name='podcastssettings',
            name='naming_scheme',
            field=models.CharField(default='$podcast_slug/$episode_slug', help_text='Scheme used to compile the episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='Episode Naming Scheme'),
        ),
        migrations.AlterField(
            model_name='podcastssettings',
            name='storage_directory',
            field=models.CharField(default='/data', help_text='Root directory of where the podcast episodes are downloaded to', max_length=255, validators=[podcasts.validators.validate_path], verbose_name='Storage Directory'),
        ),
    ]
