# Generated by Django 2.2.4 on 2019-09-01 11:34

from django.db import migrations, models
import podcasts.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_episode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=podcasts.models.common.cover_image_filename, verbose_name='Cover Image'),
        ),
    ]
