# Generated by Django 2.0 on 2018-05-09 21:41

from django.db import migrations, models
import django.db.models.deletion
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('podcasts', '0003_auto_20180509_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_directory', models.CharField(default='$HOME/', max_length=255, validators=[podcasts.validators.validate_path], verbose_name='Storage Directory')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='$HOME/', recursive=True, verbose_name='File Location'),
        ),
    ]
