# Generated by Django 2.2.4 on 2019-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20190901_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Episode Link'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='feed_url',
            field=models.URLField(max_length=2048, unique=True, verbose_name='Feed URL'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Podcast Link'),
        ),
    ]
