# Generated by Django 2.0.5 on 2018-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20180526_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Reduce eye strain at night, increase awesomeness by day.', verbose_name='Dark Mode'),
        ),
    ]
