# Generated by Django 2.0 on 2018-05-10 14:54

from django.db import migrations, models
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20180509_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastssettings',
            options={'verbose_name': 'Podcasts Settings', 'verbose_name_plural': 'Podcasts Settings'},
        ),
        migrations.AddField(
            model_name='podcastssettings',
            name='naming_scheme',
            field=models.CharField(default='{podcast_slug}/{episode_title}', help_text='Scheme used to compile the episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='Episode Naming Scheme'),
        ),
        migrations.AlterField(
            model_name='podcastssettings',
            name='storage_directory',
            field=models.CharField(default='$HOME/', help_text='Root directory of where the podcast episodes are downloaded to', max_length=255, validators=[podcasts.validators.validate_path], verbose_name='Storage Directory'),
        ),
    ]
