# Generated by Django 2.2.4 on 2019-09-02 18:02

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20190902_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='chapters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
