# Generated by Django 2.0.5 on 2018-06-17 21:55

from django.db import migrations, models
import django.db.models.deletion
import podcasts.models.episode_chapter


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_listener_image_security_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DurationField(verbose_name='Chapter Start')),
                ('title', models.CharField(max_length=2047, verbose_name='Chapter Title')),
                ('link', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Chapter Link')),
                ('image_url', models.URLField(blank=True, max_length=2047, null=True, verbose_name='Chapter Image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=podcasts.models.episode_chapter.chapter_image_filename, verbose_name='Chapter Image')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='podcasts.Episode', verbose_name='Episode of Chapter')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='episodechapter',
            unique_together={('episode', 'starttime')},
        ),
    ]
