# Generated by Django 2.0 on 2018-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_episode_download_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='sort_order_episodes',
            field=models.CharField(choices=[('Content', (('title', 'Title'), ('author', 'Author'), ('title', 'Title'))), ('Metadata', (('downloaded', 'Download Date'), ('published', 'Publishing Date'), ('itunes_duration', 'Duration')))], default='-published', max_length=16, verbose_name='Sort Episodes By'),
        ),
        migrations.AddField(
            model_name='listener',
            name='sort_order_podcasts',
            field=models.CharField(choices=[('Content', (('title', 'Title'), ('author', 'Author'), ('title', 'Title'))), ('Metadata', (('last_episode_date', 'Last Published Episode'), ('num_episodes', 'Number of Episodes')))], default='title', max_length=16, verbose_name='Sort Podcasts By'),
        ),
    ]
