# Generated by Django 2.0.9 on 2018-12-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20180617_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodechapter',
            options={'ordering': ['starttime'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
    ]
