# Generated by Django 2.0 on 2018-05-15 21:00

from django.db import migrations, models
from django.db.transaction import atomic
from django.template.defaultfilters import slugify
import podcasts.validators


@atomic
def add_slugs(apps, schema_editor):
    Episode = apps.get_model("podcasts", "Episode")
    db_alias = schema_editor.connection.alias
    for episode in Episode.objects.using(db_alias).iterator():
        episode.slug = slugify(episode.title)
        episode.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20180514_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(add_slugs),
        migrations.AlterField(
            model_name='listener',
            name='sort_order_episodes',
            field=models.CharField(choices=[('Content', (('title', 'Title'),)), ('Metadata', (('downloaded', 'Download Date (Earliest First)'), ('-downloaded', 'Download Date (Latest First)'), ('published', 'Publishing Date (Earliest First)'), ('-published', 'Publishing Date (Latest First)'), ('itunes_duration', 'Duration (Shortest First)'), ('-itunes_duration', 'Duration (Longest First)')))], default='-published', max_length=16, verbose_name='Sort Episodes By'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='sort_order_podcasts',
            field=models.CharField(choices=[('Content', (('title', 'Title'),)), ('Metadata', (('last_episode_date', 'Last Published Episode'), ('num_episodes', 'Number of Episodes')))], default='title', max_length=16, verbose_name='Sort Podcasts By'),
        ),
        migrations.AlterField(
            model_name='podcastssettings',
            name='naming_scheme',
            field=models.CharField(default='$podcast_slug}/$episode_title', help_text='Scheme used to compile the episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='Episode Naming Scheme'),
        ),
    ]
