# Generated by Django 2.0 on 2018-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20180515_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
