# Generated by Django 2.0 on 2018-05-16 17:45

from django.db import migrations, models
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20180515_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastssettings',
            name='inpath_dateformat',
            field=models.CharField(default='Y-m-d_Hi', help_text='Scheme used to compile the episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='Episode Naming Scheme'),
        ),
        migrations.AlterField(
            model_name='podcastssettings',
            name='naming_scheme',
            field=models.CharField(default='$podcast_slug/$episode_title', help_text='Scheme used to compile the episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='Episode Naming Scheme'),
        ),
    ]
