# Generated by Django 2.0 on 2018-05-16 18:39

from django.db import migrations, models
import podcasts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20180516_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastssettings',
            name='inpath_dateformat',
            field=models.CharField(default='Y-m-d_Hi', help_text='Scheme used to compile date segments in episode download filenames', max_length=255, validators=[podcasts.validators.validate_naming_scheme], verbose_name='In-Path Date Format'),
        ),
    ]
