# Generated by Django 2.0 on 2018-05-19 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20180516_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Podcast Added'),
            preserve_default=False,
        ),
    ]
