name: Docker

on:
  push:
    branches: [ $default-branch ]
    tags:
      - "*"
  pull_request:

jobs:
  docker:
    uses: janw/workflows/.github/workflows/docker.yaml@main
    with:
      build-platforms: linux/amd64
