name: Linters

on:
  pull_request:

jobs:
  gitlint:
    uses: janw/workflows/.github/workflows/gitlint.yaml@main
    with:
      first-commit: abb56f5

  pre-commit:
    uses: janw/workflows/.github/workflows/pre-commit.yaml@main
